/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.vsiwest.columnar.java-conventions")
}

dependencies {
    implementation(project(":vector-like"))
    implementation(project(":trie"))
    implementation("com.squareup.okio:okio:3.0.0-alpha.11")
}

description = "cursor"
