package uring


// @formatter:off
sealed class uring_evt(val opConstant: UInt) {
    object OpNop : uring_evt(IORING_OP_NOP)
    object OpReadv : uring_evt(IORING_OP_READV)
    object OpWritev : uring_evt(IORING_OP_WRITEV)
    object OpFsync : uring_evt(IORING_OP_FSYNC)
    object OpReadFixed : uring_evt(IORING_OP_READ_FIXED)
    object OpWriteFixed : uring_evt(IORING_OP_WRITE_FIXED)
    object OpPollAdd : uring_evt(IORING_OP_POLL_ADD)
    object OpPollRemove : uring_evt(IORING_OP_POLL_REMOVE)
    object OpSyncFileRange : uring_evt(IORING_OP_SYNC_FILE_RANGE)
    object OpSendmsg : uring_evt(IORING_OP_SENDMSG)
    object OpRecvmsg : uring_evt(IORING_OP_RECVMSG)
    object OpTimeout : uring_evt(IORING_OP_TIMEOUT)
    object OpTimeoutRemove : uring_evt(IORING_OP_TIMEOUT_REMOVE)
    object OpAccept : uring_evt(IORING_OP_ACCEPT)
    object OpAsyncCancel : uring_evt(IORING_OP_ASYNC_CANCEL)
    object OpLinkTimeout : uring_evt(IORING_OP_LINK_TIMEOUT)
    object OpConnect : uring_evt(IORING_OP_CONNECT)
    object OpFallocate : uring_evt(IORING_OP_FALLOCATE)
    object OpOpenat : uring_evt(IORING_OP_OPENAT)
    object OpClose : uring_evt(IORING_OP_CLOSE)
    object OpFilesUpdate : uring_evt(IORING_OP_FILES_UPDATE)
    object OpStatx : uring_evt(IORING_OP_STATX)
    object OpRead : uring_evt(IORING_OP_READ)
    object OpWrite : uring_evt(IORING_OP_WRITE)
    object OpFadvise : uring_evt(IORING_OP_FADVISE)
    object OpMadvise : uring_evt(IORING_OP_MADVISE)
    object OpSend : uring_evt(IORING_OP_SEND)
    object OpRecv : uring_evt(IORING_OP_RECV)
    object OpOpenat2 : uring_evt(IORING_OP_OPENAT2)
    object OpEpollCtl : uring_evt(IORING_OP_EPOLL_CTL)
    object OpSplice : uring_evt(IORING_OP_SPLICE)
    object OpProvideBuffers : uring_evt(IORING_OP_PROVIDE_BUFFERS)
    object OpRemoveBuffers : uring_evt(IORING_OP_REMOVE_BUFFERS)
    object OpTee : uring_evt(IORING_OP_TEE)
    object OpShutdown : uring_evt(IORING_OP_SHUTDOWN)
    object OpRenameat : uring_evt(IORING_OP_RENAMEAT)
    object OpUnlinkat : uring_evt(IORING_OP_UNLINKAT)
    object OpLast : uring_evt(IORING_OP_LAST)
}

//@formatter:on
