/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.vsiwest.columnar.java-conventions")
}

dependencies {
    implementation("org.bouncycastle:bcprov-jdk15on:1.69")
    implementation("org.jetbrains.kotlinx:kotlinx-datetime-jvm:0.3.0")
}

description = "vector-like"
